# -*- coding: utf-8 -*-
"""Ai based resume screening even non ATS resume.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1II9smlWaUgnHUa15faaFpQPpHsJPDzvl
"""

!pip install gradio sentence-transformers scikit-learn pytesseract pillow docx2txt pandas
!apt-get install -y tesseract-ocr

import gradio as gr
import pandas as pd
import pytesseract
from PIL import Image
import docx2txt
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import tempfile
import os

# Load AI model
model = SentenceTransformer("all-MiniLM-L6-v2")

def extract_text(file_path):
    try:
        if file_path.endswith(".docx"):
            return docx2txt.process(file_path)

        elif file_path.endswith(".txt"):
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                return f.read()

        elif file_path.lower().endswith((".png", ".jpg", ".jpeg")):
            image = Image.open(file_path)
            return pytesseract.image_to_string(image)

    except:
        return ""

    return ""

def analyze_resumes(job_description, files, threshold):

    if not files:
        return "Please upload resumes.", None

    job_embedding = model.encode(job_description)
    results = []

    for file in files:
        text = extract_text(file.name)

        if not text or len(text.strip()) < 20:
            score = 0.0
        else:
            resume_embedding = model.encode(text)
            score = cosine_similarity(
                [resume_embedding], [job_embedding]
            )[0][0] * 100

        results.append({
            "Resume Name": os.path.basename(file.name),
            "Match Percentage": round(score, 2)
        })

    df = pd.DataFrame(results).sort_values(
        by="Match Percentage", ascending=False
    )

    selected = df[df["Match Percentage"] >= threshold]
    rejected = df[df["Match Percentage"] < threshold]

    summary = f"""
Total resumes processed: {len(df)}
Selected (≥{threshold}%): {len(selected)}
Rejected (<{threshold}%): {len(rejected)}
"""

    return summary, df

# Gradio UI
interface = gr.Interface(
    fn=analyze_resumes,
    inputs=[
        gr.Textbox(
            lines=5,
            label="Job Description",
            value="Looking for a Python developer with experience in Machine Learning, APIs, data analysis, and NLP."
        ),
        gr.File(file_count="multiple", label="Upload Resumes"),
        gr.Slider(0, 100, value=80, label="Match Threshold (%)")
    ],
    outputs=[
        gr.Textbox(label="Summary"),
        gr.Dataframe(label="Resume Match Results")
    ],
    title="🤖 AI Resume Screening System (Gradio)",
    description="OCR + Semantic AI based resume matcher. Supports scanned resumes, DOCX, and TXT files."
)

interface.launch(share=True)